# Generated by Django 5.0.3 on 2024-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('destination', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
            ],
        ),
    ]
