# Generated by Django 5.0.3 on 2024-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='image',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='train',
            name='plan',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
